modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="northcommunity"
version="${file.jarVersion}"
displayName="North Community"
logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"


description='''
Mod by TrickyAMT
'''

[[dependencies.northcommunity]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.northcommunity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
